force-app/main/default/objects/Badge__c/Badge__c.object-meta.xml
<CustomObject>
    <description>Used to store badges from Clients.</description>
    <label>Badge</label>
    <nameField>
        <label>Badge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge__c/fields/Badge_Number__c.field-meta.xml
<CustomField>
    <fullName>Badge_Number__c</fullName>
    <description>This field is used to fill information regarding the badge number.</description>
    <inlineHelpText>Use this field to fill a badge number.</inlineHelpText>
    <label>Badge Number</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Badge_Assignment__c/Badge_Assignment__c.object-meta.xml
<CustomObject>
    <description>This is a junction object used to store records related to Contacts and Badges__c objects.</description>
    <label>Badge Assignment</label>
    <nameField>
        <displayFormat>BAN-{000000}</displayFormat>
        <label>Badge Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Badge Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge_Assignment__c/fields/BadgeId__c.field-meta.xml
<CustomField>
    <fullName>BadgeId__c</fullName>
    <description>This field is used to relate a relationship between Badge Assignment and Badge.</description>
    <label>Badge</label>
    <referenceTo>Badge__c</referenceTo>
    <relationshipLabel>Badge Assignments</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Badge_Assignment__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <description>This field is used to relate a relationship between Badge Assignment and Contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Badge Assignments</relationshipLabel>
    <relationshipName>Badges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BadgeAssigment.cls
public with sharing class BadgeAssigment {
    
    @AuraEnabled
    public static String validateBadgeRecord (String badgeNumber, String contactId){
        
        List<Badge__c> lstBadge =  [ SELECT Id, Badge_Number__c 
                                       FROM Badge__c 
                                      WHERE Badge_Number__c =: badgeNumber 
                                      LIMIT 1 ];
        
        If (lstBadge.size() > 0){
            return validateBadgeAssignment(lstBadge[0].Id, contactId);
        } else {
            return 'Invalid';
        } 
    }
    
    @AuraEnabled
    public static String validateBadgeAssignment (String badgeId, String contactId){
        
        List<Badge_Assignment__c> lstBadgeAssigment =  [ SELECT Id, BadgeId__c, ContactId__c 
                                                           FROM Badge_Assignment__c 
                                                          WHERE BadgeId__c =: badgeId 
                                                            AND ContactId__c !=: contactId 
                                                          LIMIT 1 ];
         
        If (lstBadgeAssigment.size() > 0){
            return badgeId + ' - Warning';
        } else {
            return createBadgeAssignment(badgeId, contactId);
        } 
    }
    @AuraEnabled
    public static String createBadgeAssignment (String badgeId, String contactId){
        
        try{
            Badge_Assignment__c badgeAssigment = new Badge_Assignment__c( BadgeId__c = badgeId, 
                                                                          ContactId__c = contactId );
            insert badgeAssigment;
            return 'Created';
        } catch(AuraHandledException e){
			throw new AuraHandledException(e.getMessage());            
        }
    }
}